backend:
  name: github
  repo: org/repo
collections:
- create: true
  fields:
  - label: Title
    name: title
    widget: string
  - default: false
    label: Draft
    name: draft
    widget: boolean
  - date_format: YYYY-MM-DD
    format: YYYY-MM-DD HH:mm
    label: Publish Date
    name: date
    time_format: HH:mm
    widget: datetime
  - label: Cover Image
    name: image
    required: false
    tagname: ""
    widget: image
  - hint: Main content goes here.
    label: Body
    name: body
    widget: markdown
  folder: content/articles
  label: Articles
  media_folder: ""
  name: articles
  public_folder: ""
locale: en-us
media_folder: static
site_url: https://fence-io.github.io/website/.pr/92/
